### ISSUE TITLE
Please be consistent with the version number

### ISSUE THREAD

**Issue by sjackman** [mjsull/Easyfig#1]
In some places the version is `2.1.0` (the GitHub tag) and others just `2.1` (the tarballs and app name). Please be consistent and use `2.1.0` throughout.
See [Semantic Versioning](http://semver.org/).

**Comment by sjackman** [comment]
Likewise please be consistent with the character case of the package name. In some places it's `EasyFig` and other places it's `Easyfig`. Which is preferred?

**Comment by sjackman** [comment]
I've created a Homebrew Cask formula for EasyFig.
https://github.com/caskroom/homebrew-cask/pull/12825

**Comment by mjsull** [comment]
Hi Shaun,
Sorry for taking so long to get to this. Had a paper and my PhD thesis come back from review, everything should be more consistent now.

-Mitch

**Comment by sjackman** [comment]
No worries, Mitch. I'm on parental leave myself. Thanks for fixing this up. Cheers, Shaun
