### ISSUE TITLE
DNA sequence comparison - graphic representation

### ISSUE THREAD

**Issue by NFraz** [mjsull/Easyfig#10]
Hello,

I have uploaded the same DNA sequence to the Easyfig software (.gbk files) with different names to test the graphical representation. Instead of 100% similarity I got some areas where the similarity is below 100%.

Can anyone explain this? If it is the very same sequence it should give 100% similarity for the whole sequence, and a graphical representation with 100% similarity...

Thanks in advance,
Nelson

[Comparison.pdf](https://github.com/mjsull/Easyfig/files/1407604/Comparison.pdf)

**Comment by mjsull** [comment]
Hi Nelson,

Easyfig uses BLAST which performs a local alignment. So in addition to your genome aligning along it's entire length at 100% identity there are also smaller hits between non-exact repeat regions in the genome. If you don't want to show these hits you can adjust the settings for which BLAST hits are reported (i.e. minimum length or identity) in Image->BLAST.

-Mitch

**Comment by NFraz** [comment]
Hi Mitch,

Thank you so much for the quick reply. I already tried to adjust the settings. However, I cannot fully take out from the picture all these non-exact repeated regions, yet.
Anyway, thanks for the explanation. 

Cheers,
N
