### ISSUE TITLE
Rectangles in Feature name

### ISSUE THREAD

**Issue by NFraz** [mjsull/Easyfig#11]
Hi everyone,

I have triangles appearing in Fetaure Labels (please see picture). Does anyone knows how to remove them? I am wondering if this is something wrong in the genebank files... However, for the same file I have Features appearing with and without the rectangles...

Many thanks,
Nelson

[TestFigure.pdf](https://github.com/mjsull/Easyfig/files/1410532/TestFigure.pdf)

**Comment by mjsull** [comment]
Hi Nelson,

The bmp output has a rather limited character set - I would try creating an SVG and then converting it to another format using Inkscape/your preferred tool.

-Mitch

**Comment by NFraz** [comment]
OK, it seems the better to do. 
Thanks again.
N

**Comment by NFraz** [comment]
Hi everyone,

Does anyone knows how to define the proper value for the Blast minimal length when comparing bacterial genomes?

I have tested the same genome against itself and depending on the genome I get 100% similarity using different values for the Blast minimal length...

Many thanks,
Nelson

**Comment by mjsull** [comment]
Hi Nelson,

Sorry missed this. Minimum length is just the length of the blast hits Easyfig will show. It has nothing to do with the similarity of the regions that aligned.

-Mitch
