### ISSUE TITLE
can't present my colour in the picture

### ISSUE THREAD

**Issue by offyo3** [mjsull/Easyfig#13]
Hi,
Can anyone suggest me to change or present the of the ORF in the picture? I added the code presented in the example 1 and 2 such as /colour=10. However, nothing was changed in the picture. Thanks in advance.

Best regards,
Oof

**Comment by bawee** [comment]
Are you trying to draw `gene` or `cds`? Check that the right box is checked in the `Image` > `annotation` menu option

**Comment by offyo3** [comment]
It's done. Thank a lot ^ ^.
