### ISSUE TITLE
other input /alignment formats?

### ISSUE THREAD

**Issue by dcopetti** [mjsull/Easyfig#14]
Hello,

I find Easyfig very convenient to represent a comparison between 2 or more sequences in a linear space.
I wonder if it is (or will?) be possible to upload features in other formats: e.g. annotation in gff3/bed format, nucmer/any table alignment, and so on. If not, do you know of any other tool to visualize alignments and annotations between regions of a genome? possibly that will work also well above 5 Mb - I work with eukayotic genomes.
Also, is there a maximum genome size that the tool can work with?
thanks,

Dario

**Comment by mjsull** [comment]
There is no maixmum, but it will be very slow on Euks.

Unfortunately I don't really have the time to incorporate other formats/aligners.
