### ISSUE TITLE
Add colour feature qualifier to GenBank file

### ISSUE THREAD

**Issue by rzzju** [mjsull/Easyfig#16]
When I using the Colour the coding-sequence (CDS) features function by manually adding one /colour feature qualifier to my GenBank file (i.e. /colour=16), the genes after I would like to change the colour disappeared in the final image. For example, I would like to change the tenth gene into the red colour, but the genes from the eleventh to the last cannot be displayed any more. The demo data works fine with me to change the colour.

**Comment by mjsull** [comment]
Hi,

Can you check that you are not using tabs instead of 4 spaces.

-Mitch

**Comment by luongphekidz07** [comment]
Dear all,
I have the same problem also. Could anyone suggest the solution

**Comment by rzzju** [comment]
Hi,


Can you check that you are not using tabs instead of 4 spaces.


Zhi


On 01/23/2019 09:40, luongphekidz07 wrote:

Dear all,
I have the same problem also. Could anyone suggest the solution

**Comment by luongphekidz07** [comment]
Hello, I would like to explain clearer. I open the gb file and edit the gb file manually. Here is the example:

     CDS             <1..279
                     /db_xref="SEED:fig|6666666.402485.peg.14"
                     /translation="MIIVLGSQKGGVGKSTLAVSIAAYLMSLGNRVIIVDADDQKSVL
                     TWYNNRPEDLPHIPVTGATGNIKAMLKEHEKSYDFVIADCAGRDSAEMRSGLMAADVF
                     ISPLRPSQMDLDVVPHTCSVFTAAKDFNGDVRGYLVLNMTPTNMFVNEANEAAEVLKD
                     YPEMHLANSRVCDRKAHRDAWAESMTIFETQNDKAQQEIEALVKEVIL"
                     /product="ParA-like_protein"
                     /transl_table=11


Then I entered and added the /colour=10

     CDS             <1..279
                     /db_xref="SEED:fig|6666666.402485.peg.14"
                     /translation="MIIVLGSQKGGVGKSTLAVSIAAYLMSLGNRVIIVDADDQKSVL
                     TWYNNRPEDLPHIPVTGATGNIKAMLKEHEKSYDFVIADCAGRDSAEMRSGLMAADVF
                     ISPLRPSQMDLDVVPHTCSVFTAAKDFNGDVRGYLVLNMTPTNMFVNEANEAAEVLKD
                     YPEMHLANSRVCDRKAHRDAWAESMTIFETQNDKAQQEIEALVKEVIL"
                     /product="ParA-like_protein"
		    /color=255 0 0

I can not used 4 spaces. Could you tell me which software that you used for editing the gb file?

**Comment by luongphekidz07** [comment]
![image](https://user-images.githubusercontent.com/28089052/51577231-78df4200-1efc-11e9-9cd3-8b3548687e9e.png)

**Comment by rzzju** [comment]
Please verify the what is in front of /color, only spaces are allowed. In some situation, there is a tab, instead of space.


Zhi

**Comment by rzzju** [comment]
Also, the word "color" should be "colour"

Zhi




在 2019-01-23 09:49:02，"luongphekidz07" <notifications@github.com> 写道：
