### ISSUE TITLE
Issue with reverse subregion

### ISSUE THREAD

**Issue by cswift3** [mjsull/Easyfig#19]
Hello,
I am trying to use EasyFig to compare two gene clusters. I have the gene clusters in two genbank files. I want to reverse some of the gene arrows in each genbank file. However, when I try to use subregions to do this, I can only select one subregion per genbank file. The figure ends up being only the reversed arrow. How can I reverse the gene arrow (subregion) but still keep the other features (gene arrows) from the genbank file?

Thanks for your help in advance.

**Comment by mjsull** [comment]
Hi,

It sounds like you want to reverse a specific region in a genome and leave the rest in the original orientation?

The subregion feature is specifically for displaying part of the genome, so if it is set only that part of the genome will be shown, which then can be reverse complimented if you like.

If you don't use a subregion the entire genome can be reversed also.

To achieve what you want you will probably have to edit the annotation file, which is outside the scope of what Easyfig can do.

Best,

Mitch
