### ISSUE TITLE
NameError: name 'genBlast' is not defined

### ISSUE THREAD

**Issue by yjx1217** [mjsull/Easyfig#2]
Hello,

I got the following error when invoking Easyfig from the command line on Linux. The Easyfig version that I am using is "Version 2.2.2 10.08.2015". Could you help me to figure out what might cause this error?

 python /home/yjx/Programs/Easyfig/Easyfig.py -o test -blastn  chrI.embl 1 40850 R chrI.embl 179930 219929
Traceback (most recent call last):
  File "/home/yjx/Programs/Easyfig/Easyfig.py", line 10988, in <module>
    inlist = genBlast(templist, cutlist)
NameError: name 'genBlast' is not defined

Thanks!

Best,
Jia-Xing

**Comment by yjx1217** [comment]
hmm, I found out the current version at GitHub (not the released one) does not have this issue. But the "-i" option (for set min_identity cutoff for BLAST) seems not working properly. I set "-i 90" in my command line but the output still shows hits with identity < 90.

**Comment by mjsull** [comment]
Hi Jia-Xing,

Yes, someone emailed me about that bug last week, but thanks for letting me
know anyway. I have fixed it on github (as you noticed) but haven't had
time to create the new executables and update the website. I will make sure
I do it tomorrow.

When you say the output still shows hits with identity < 90 do you mean the
image or the BLAST output? The filtering is done by Easyfig after the BLAST
file has been created so that parameters can be adjusted without having to
generate a new BLAST file, so all hits will be in the BLAST output
(regardless of what settings were provided). If they aren't being filtered
in the image please let me know.

Best,

Mitchell

**Comment by yjx1217** [comment]
Dear Mitchell,

Thank you very much for the reply. About the BLAST, yes, I think the
filtering doesn't work in the image. I set min_identity cutoff as 90 but
the BLAST identity scale bar in the image still starts from 62 in my case.
So I think there might be something wrong. Also, is it possible to let
Easyfig keep the raw BLAST table result rather than  delete it after the
image was generated? If not, could you add this feature in the near future?
I think this will be very helpful in some cases. Thanks again!

Best,
Jia-Xing

On Mon, Dec 21, 2015 at 10:55 PM, mjsull notifications@github.com wrote:

> Hi Jia-Xing,
> 
> Yes, someone emailed me about that bug last week, but thanks for letting me
> know anyway. I have fixed it on github (as you noticed) but haven't had
> time to create the new executables and update the website. I will make sure
> I do it tomorrow.
> 
> When you say the output still shows hits with identity < 90 do you mean the
> image or the BLAST output? The filtering is done by Easyfig after the BLAST
> file has been created so that parameters can be adjusted without having to
> generate a new BLAST file, so all hits will be in the BLAST output
> (regardless of what settings were provided). If they aren't being filtered
> in the image please let me know.
> 
> Best,
> 
> Mitchell
> 
> On 20 December 2015 at 16:20, Jia-Xing Yue notifications@github.com
> wrote:
> 
> > hmm, I found out the current version at GitHub (not the released one)
> > does
> > not have this issue. But the "-i" option (for set min_identity cutoff for
> > BLAST) seems not working properly. I set "-i 90" in my command line but
> > the
> > output still shows hits with identity < 90.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mjsull/Easyfig/issues/2#issuecomment-166155700.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mjsull/Easyfig/issues/2#issuecomment-166434827.

## 

Jia-Xing Yue

Population Genomics and Complex Traits Group
Tour Pasteur 8eme etage
Faculté de Médecine
Institute for Research on Cancer and Aging, Nice (IRCAN)
CNRS UMR 7284 - INSERM U 1081
Université de Nice Sophia Antipolis
28 Avenue de Valombrose
06107 NICE Cedex 2
France

Lab website: http://ircan.org/index.php?Itemid=98
Personal website: http://www.iamphioxus.org/

**Comment by yjx1217** [comment]
Dear Mitchell,

I've just tried the newest version code on github and found this error
still remains. I attached the test data for your check. As you can see that
I've already specified "-i 90" in my command (run_easyfig.sh) but the
resulting plot still shows hits with identity as low as 70% (based on the
scale bar). Could you have more check about this? Thanks in advance!

Best,
Jia-Xing

On Mon, Dec 21, 2015 at 11:04 PM, Jia-Xing Yue yuejiaxing@gmail.com wrote:

> Dear Mitchell,
> 
> Thank you very much for the reply. About the BLAST, yes, I think the
> filtering doesn't work in the image. I set min_identity cutoff as 90 but
> the BLAST identity scale bar in the image still starts from 62 in my case.
> So I think there might be something wrong. Also, is it possible to let
> Easyfig keep the raw BLAST table result rather than  delete it after the
> image was generated? If not, could you add this feature in the near future?
> I think this will be very helpful in some cases. Thanks again!
> 
> Best,
> Jia-Xing
> 
> On Mon, Dec 21, 2015 at 10:55 PM, mjsull notifications@github.com wrote:
> 
> > Hi Jia-Xing,
> > 
> > Yes, someone emailed me about that bug last week, but thanks for letting
> > me
> > know anyway. I have fixed it on github (as you noticed) but haven't had
> > time to create the new executables and update the website. I will make
> > sure
> > I do it tomorrow.
> > 
> > When you say the output still shows hits with identity < 90 do you mean
> > the
> > image or the BLAST output? The filtering is done by Easyfig after the
> > BLAST
> > file has been created so that parameters can be adjusted without having to
> > generate a new BLAST file, so all hits will be in the BLAST output
> > (regardless of what settings were provided). If they aren't being filtered
> > in the image please let me know.
> > 
> > Best,
> > 
> > Mitchell
> > 
> > On 20 December 2015 at 16:20, Jia-Xing Yue notifications@github.com
> > wrote:
> > 
> > > hmm, I found out the current version at GitHub (not the released one)
> > > does
> > > not have this issue. But the "-i" option (for set min_identity cutoff
> > > for
> > > BLAST) seems not working properly. I set "-i 90" in my command line but
> > > the
> > > output still shows hits with identity < 90.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/mjsull/Easyfig/issues/2#issuecomment-166155700.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mjsull/Easyfig/issues/2#issuecomment-166434827.
> 
> ## 
> 
> Jia-Xing Yue
> 
> Population Genomics and Complex Traits Group
> Tour Pasteur 8eme etage
> Faculté de Médecine
> Institute for Research on Cancer and Aging, Nice (IRCAN)
> CNRS UMR 7284 - INSERM U 1081
> Université de Nice Sophia Antipolis
> 28 Avenue de Valombrose
> 06107 NICE Cedex 2
> France
> 
> Lab website: http://ircan.org/index.php?Itemid=98
> Personal website: http://www.iamphioxus.org/

## 

Jia-Xing Yue

Population Genomics and Complex Traits Group
Tour Pasteur 8eme etage
Faculté de Médecine
Institute for Research on Cancer and Aging, Nice (IRCAN)
CNRS UMR 7284 - INSERM U 1081
Université de Nice Sophia Antipolis
28 Avenue de Valombrose
06107 NICE Cedex 2
France

Lab website: http://ircan.org/index.php?Itemid=98
Personal website: http://www.iamphioxus.org/

**Comment by mjsull** [comment]
Hi Jia-Xing,

Should be all fixed now :)

Also if you add the "-keep" flag before your genbank files Easyfig will now keep the temp_easyfig folder with all the blast output in it.

Best,

Mitchell

**Comment by yjx1217** [comment]
Hi Mitchell,

Thank you very much for the fix and enhancement!

Best,
Jia-Xing

On Mon, Jan 25, 2016 at 4:52 PM, mjsull notifications@github.com wrote:

> Hi Jia-Xing,
> 
> Should be all fixed now :)
> 
> Also if you add the "-keep" flag before your genbank files Easyfig will
> now keep the temp_easyfig folder with all the blast output in it.
> 
> Best,
> 
> Mitchell
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mjsull/Easyfig/issues/2#issuecomment-174551057.

## 

Jia-Xing Yue

Population Genomics and Complex Traits Group
Tour Pasteur 8eme etage
Faculté de Médecine
Institute for Research on Cancer and Aging, Nice (IRCAN)
CNRS UMR 7284 - INSERM U 1081
Université de Nice Sophia Antipolis
28 Avenue de Valombrose
06107 NICE Cedex 2
France

Lab website: http://ircan.org/index.php?Itemid=98
Personal website: http://www.iamphioxus.org/
