### ISSUE TITLE
how to change color of specific targets in easyfig 

### ISSUE THREAD

**Issue by luongphekidz07** [mjsull/Easyfig#20]
When I using the Colour the coding-sequence (CDS) features function by manually adding one /colour feature qualifier to my GenBank file (i.e. /colour=10), the genes after I would like to change the colour disappeared in the final image. For example, I would like to change the tenth gene into the red colour, but the genes from the eleventh to the last cannot be displayed any more. The demo data works fine with me to change the colour.

**Comment by mjsull** [comment]
Hi,
Potentially you are using tabs instead of spaces which causes issues when parsing a genbank file.

-Mitch
