### ISSUE TITLE
blastp on translated proteins?

### ISSUE THREAD

**Issue by RvV1979** [mjsull/Easyfig#26]
Hi Mitchell, 
I am trying to use Easyfig binary to depict syntenic blocks across plant genomes. Given that most genes comprise many introns tblastx across the genome nucleotide sequences does not generate the gene-to-gene alignments that I am aiming for but rather produces many small alignments representing individual exons. 
Is there a way to generate blastp alignments based on the translated proteins? 
Thanks for your advice

**Comment by mjsull** [comment]
Hi,

Not at the moment unfortunately. The only way to do this would be
replicating the -outfmt 6 option from BLAST.
You could also try increasing the minimum length/identity/evalue of
reported BLAST hits in the Image->BLAST menu.

Best,

Mitch

**Comment by RvV1979** [comment]
Thanks for the reply. Changing the minimum length/identity/evalue of
reported BLAST hits in the Image->BLAST menu does not give me the results I
need. I realize that Easyfig was developed for prokaryote genomics but I
think that if you would ever add translated protein blast functionality it
would be a great tool for a wide community working on Eukaryote genomes,
too. Just a thought :-)
