### ISSUE TITLE
easyfig

### ISSUE THREAD

**Issue by ga23981** [mjsull/Easyfig#27]
I am trying to plot synteny of 12 genes present in a pathogenicity cluster identified in my bacterial species and want to compare it with six other bacterial species (already available genomes). However I am not able to get the plots.

I have so far:
Done a local tblastx using my pathogenicity genes (12 genes) as query and other available bacterial species (6 genomes) as subject (one at a time) to generate 6 tblastx output tables (outfmt 6).
Used the tblastx output as input blast files for easyfig and fasta files of query genes and blast hits as input annotation files for easyfig.

All it gives me just three straight lines. I understand I am doing something wrong here.

I have following questions:

Can I use unannotated fasta files under annotation files or I have to use only .gb files?

Do I get only top blast hits from mt blast output or use the blast output as such under blast files in easyfig. In the current form my blast output file has multiple hits against the each gene.

If I have to use .gb files then do the gb files have to be specific to the gene coordinates extracted from the whole genome gb file? 

Is windows and linux version the same in terms of features that are used to generate the figure?

Could you please look into my files and suggest. If you can then I will share my files with you and it will be a great help.

Thank you
GA

**Comment by mjsull** [comment]
Unannotated fasta files are time.

All blast hits will be drawn that satisfy the conditions in the blast menu, you can adjust these values to get more or less blast hits drawn. 

Windows and linux versions are identical.
