### ISSUE TITLE
Impossible to draw features

### ISSUE THREAD

**Issue by ATVincent** [mjsull/Easyfig#3]
Hello,

I am using EasyFig version 2.2.2 for Mac OSX. For some GenBank files (for example this one: http://www.ncbi.nlm.nih.gov/nuccore/NC_009348.1), EasyFig cannot draw the features (CDS, tRNA ...). 

Is there something wrong (particularities) with this GenBank file? I tried on Windows and I have the same issue.

Thank you!

**Comment by mjsull** [comment]
Hi,

Have you unchecked "filter small blast hits/annotations" it is under
Image->blast in the drop down menu?

Best,

Mitchell

**Comment by ATVincent** [comment]
Thank you, it was effectively the "filter small blast hits/annotations".

Antony

**Comment by mjsull** [comment]
Excellent :)
