### ISSUE TITLE
Incorrect drawing for reverse exons of CDS features

### ISSUE THREAD

**Issue by fborne2** [mjsull/Easyfig#30]
Hi,

I'm having trouble to draw exons for CDS that are in reverse direction. In my genbank files, exons are defined as follows:
join(complement(59762..60896),complement(60948..60968))

Only the last exon (the one on the left) of my reverse genes and the dashes joining the different exons of the genes are displayed.

It works well for exons in the forward genes defined as follows:
join(49140..49167,49241..50136)

I am using the python script 2.2.3 

Do you know what is wrong?
Thank you,

Best,

Flora

**Comment by mjsull** [comment]
Hi, I think the correct way to annotate that in genbank is

complement(join(59762..60896,60948..60968))

That will work for Easyfig at least.
