### ISSUE TITLE
Easyfig open interactive interface continually and automatically

### ISSUE THREAD

**Issue by ghost** [mjsull/Easyfig#31]
Hi,   
I encountered a very strange issue while using Easyfig_2.2.5_win version, my windows version is 1809, and I did not install any python related packages. But when I open Easyfig, it will open interactive interface continually and automatically, like `Create Figure`, `Add folder`, and others.    
Please help to clarify this issue.

Many thanks!
Lucas

**Comment by liuchenwentianfangfang** [comment]
Hi,
I also encountered the same problem. Have you solved it?
thanks
Wentian Liu

**Comment by ghost** [comment]
> Hi,
> I also encountered the same problem. Have you solved it?
> thanks
> Wentian Liu

I can't find a solution based on the release version. What I can do is to rebuild the project and generate the executable program myself, and it works, fortunately.

**Comment by liuchenwentianfangfang** [comment]
thanks

**Comment by liyinshu** [comment]
I had the same problem, and I download 2.2.5 version, but also appear this problem. Have you solved it [now？Thanks

**Comment by liyinshu** [comment]
> I had the same problem, and I download 2.2.5 version, but also appear this problem. Have you solved it [now？Thanks

And I found some python related packages，Is it a factor that affects this？
