### ISSUE TITLE
Easyfig does not run 

### ISSUE THREAD

**Issue by ghost** [mjsull/Easyfig#38]
Hi, 

I'm using Ubuntu 20 LTS and I'm trying to run Easyfig. Once that I've already submitted the files (both gff and blast) and press create figure it does not do anything. It just display the "cancel figure" message but it does not show the "creating figure" message in the orange box 

![easyfig](https://user-images.githubusercontent.com/38421552/100526862-a77e7180-3192-11eb-91a9-49b81d32aec2.png)

Any recommendation?

**Comment by mjsull** [comment]
Hi, if you try running the GUI from the python script can you tell me if you see any error messages coming up in the console.

Also Easyfig will only work with genbank files, not gffs.
