### ISSUE TITLE
Easyfig visualizes differences in genomes that are identical

### ISSUE THREAD

**Issue by solveigmo** [mjsull/Easyfig#44]
I have compared two plasmid sequences that are almost identical (0 SNPs identified by snippy and progressiveMAUVE). Also, alignment of the sequences in CLC and MEGA have shown a perfect alignment except the first 1031 bp, which are only present in one of the plasmids. However, in the figure created by EasyFig, several differences are indicated. Any idea what has happened? I have tried to take a look at the .out file from BLAST, and it seems that some regions are compared several times etc. Could this be the reason fro the errors in the figure? Any suggestions on how to solve this? :)

**Comment by mjsull** [comment]
On the default settings Easyfig will show all blast hits, including internal blast hits. So what you're seeing are repeat regions aligning to each other. You can adjust the minimum length of the blast hits to have them not show up.
