### ISSUE TITLE
What do I upload as Blast files?

### ISSUE THREAD

**Issue by GREATER93** [mjsull/Easyfig#46]
Hello there! Thanks for this very useful tool.

I am new to using Easyfig. My aim is to compare some bacterial genomes and identify sites of mutations or alterations. The genomes are same bacteria, but one is wildtype and the other is an evolved variant. After WGS, I obtained the sequences in fasta formats. I have also performed annotation for the two genomes.

My question is what do I upload in the Blast files column? In the annotation files, I uploaded the annotation files in genebank format; correct?

Kindly help! Thank you very much.

**Comment by mjsull** [comment]
Hi, you can upload blast files generated by command-line blast using the format -outfmt 6. The top genome should be the subject and bottom the query.

Alternatively you can get Easyfig to generate the blast output for you.
