### ISSUE TITLE
Issues with EasyFig 2.2.5 Blast Files

### ISSUE THREAD

**Issue by jdcfc** [mjsull/Easyfig#47]
Hi there,

I'm hoping someone can help me resolve an issue with BLAST files when trying to create a figure.

I am using a Windows 64-bit machine. I have downloaded the latest version of ncbi-blast-2.12.0+-win64. I have shown the software where the blast executables are on my computer through the "choose blast location" button. After adding two GenBank files, I will click "generate blastn files" and I will see two files be created in the working directory, namely: "1.easyfig.fa" and "2.easyfig.fa". Then, in the Blast Files tab, there will be a file ending in "/12.easyfig.out".

However, when finally clicking "create figure", an error message pops up saying: "A selected file does not exist". Also, within the working directory, there is no file ending in "/12.easyfig.out".

I was wondering if there was anything I could do to fix this?

Thank you for your help!

**Comment by 18289733597** [comment]
Hello, I have encountered the same problem as you before. My problem is that there is a space symbol on the output folder path. Just remove the space.

**Comment by jdcfc** [comment]
> Hello, I have encountered the same problem as you before. My problem is that there is a space symbol on the output folder path. Just remove the space.

Hi 18289733597,

Thank you so much for your help! This has fixed the issue. I really appreciate it :)
