### ISSUE TITLE
cannot generate tblastx 

### ISSUE THREAD

**Issue by Yoongi123** [mjsull/Easyfig#48]
I was working well the whole day but when I tried to compare 3 genebank files,suddenly it generate blastn files but not blastx files anymore. When I clicked crate blastx file, if re-creates the blastn files again. Does anyone know how to solve? please , thanks in advance

**Comment by mjsull** [comment]
Hi, it isn't running blastx, rather it's running tblastx which translates nucleotides to all open reading frames in both the query an the reference. For a lot of applications this will be quite similar to the blastn
