### ISSUE TITLE
unfixed error in current release: "name 'genBlast' is not defined"

### ISSUE THREAD

**Issue by jvollme** [mjsull/Easyfig#5]
Hi,
I'm using EasyFig V2.2.2 (the latest release obtained from your "Downloads" section).
It works fine in GUI-mode, but when I try to run EasyFig from the commandline  like this:
`Easyfig -o prelim_easyfig.bmp -blastn -filter myfasta1.fasta myfasta2.fasta`
I get this error:
```
Traceback (most recent call last):
  File "<string>", line 10988, in <module>
NameError: name 'genBlast' is not defined
```
This problem was reported already in Issue #2, but the poster said that this issue only occured in the official release, not in the most current github-version.
Therefore I tried to clone the github-version instead. However, in that case I only get an "Easyfig.py" and an "setup.py" file. None of them seem to run on my System (Linux Ubuntu 14.04). 
Error when running "setup.py":
```
  File "setup.py", line 4, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named cx_Freeze
```
Error when running "EasyFig.py":
```
Traceback (most recent call last):
  File "Easyfig.py", line 11452, in <module>
    root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /tmp/staden-generic-root/lib/tcl8.6 /usr/lib/tcl8.6 /lib/tcl8.6 /usr/library /library /tcl8.6.1/library /tcl8.6.1/library



This probably means that Tcl wasn't installed properly.
```
How do I Install the current github-version?

Would it be possible to exchange the current release in the "Download" section by a version where this bug is fixed (GUIs can be nice, but I would like to automize this task by including it in my shell scripts)?

EDIT:
The same problem also occurs when running the released Python-version  "Easyfig.py" from your Download-section:
```
  File "/home/john/Downloads/Easyfig.py", line 10988, in <module>
    inlist = genBlast(templist, cutlist)
NameError: name 'genBlast' is not defined
```

**Comment by chrisgulvik** [comment]
I see the same error after command line execution of v2.2.2:

```
Traceback (most recent call last):
  File "<string>", line 10973, in <module>
NameError: name 'getGCcontent' is not defined
```

**Comment by mjsull** [comment]
Hi, running the github version from the command-line should now work without Tkinter installed.

If you want to run the GUI version you can install tkinter (the GUI) with $ sudo apt-get install python-tk

I will hopefully have time to update the versions on the site tonight.

**Comment by Bio1nform** [comment]
Hi,
I am new to easyfig. it is easy and great.
I cannot run Easyfig_example2 from Easyfig_win_2.1.
-uploaded three gbk file.
-uploaded two blastn file

Click Create figure  ---says Too many blast files.

Thanks

**Comment by Anupmas** [comment]
I get the same error running on the commandline. 

Traceback (most recent call last):
  File "/mnt/nfs1/Databases/softwares/Easyfig.py", line 10992, in <module>
    inlist = genBlast(templist, cutlist)
NameError: name 'genBlast' is not defined

I am using the version 2.2.2
