### ISSUE TITLE
Easyfig was out of my control

### ISSUE THREAD

**Issue by wy931221** [mjsull/Easyfig#55]
My computer system is windows 10. I recently downloaded the Easyfig. version 2.1 and 2.2. But When I open Easyfig, it will open many interactive interface continually and automatically, like Create Figure, Add folder, and others.I have downloaded the latest version 2.2.5，also has the same problem and appear this window. And my folder name have changed to the english. I am very much looking forward to receiving your solution. If so, I would appreciate it! Thank you very much.

**Comment by mjsull** [comment]
I think python 2.7 is causing issues with newer computers.

I have a python 3 development version here that you can try:

https://raw.githubusercontent.com/mjsull/Easyfig/python3/Easyfig.py
