### ISSUE TITLE
Easyfig.py not running on windows 10 python 3.9.6

### ISSUE THREAD

**Issue by kkj15dk** [mjsull/Easyfig#57]
When trying to run easyfig from the command line, it throws an error.
What is going on? Do i not have a compatible version of python?

![image](https://user-images.githubusercontent.com/76531122/211535172-426d8442-0ce9-4556-bb7b-97b030d1c3fa.png)

the Easyfig folder is a folder with only Easyfig.py

**Comment by mjsull** [comment]
Hi,

Easyfig was written in Python 2.7 and won't work with Python 3.

You can try the the binary from here https://mjsull.github.io/Easyfig/files.html

Run it with python 2.7

I also have a python 3 version in devlopment here

https://raw.githubusercontent.com/mjsull/Easyfig/python3/Easyfig.py
