### ISSUE TITLE
Command line with -blast_files option . Error Report.

### ISSUE THREAD

**Issue by YantingHu** [mjsull/Easyfig#59]
$ python ~/hyt/Easyfig.py -o aa.bmp Rhdel01G0032900.gb Rhdel01G0032300.gb -blast_files Rhdel01G0032900_Rhdel01G0032300.blast.out 

"
Tab found in genbank file, this may cause some Features to be missed, please remove tabs.Tab found in genbank file, this may cause some Features to be missed, please remove tabs.Traceback (most recent call last):
  File "/home/huyanting/hyt/Easyfig.py", line 11466, in <module>
    blastoutline, cutlist, filter, legend, legname)
  File "/home/huyanting/hyt/Easyfig.py", line 6029, in draw
    maxcut = featlengths[i/2]
IndexError: list index out of range
"

However these three inputs worked well with GUI.

Needing help for  examples of blast files and command line.

Thaks a lot!

**Comment by mjsull** [comment]
Hi, all the arguments need to come before the genbank files. 

python ~/hyt/Easyfig.py -o aa.bmp -blast_files Rhdel01G0032900_Rhdel01G0032300.blast.out Rhdel01G0032900.gb Rhdel01G0032300.gb  should work fine.
