### ISSUE TITLE
Feature request: allow specifying a defined minimum value for calulating color gradients

### ISSUE THREAD

**Issue by jvollme** [mjsull/Easyfig#6]
The Easyfig plots use a color gradient to specify the degree of similarity between the compared genome regions.
It is possible to specifiy the color for minimum and maximum points, but it is not possible to define a specific minimum value for calculating the gradient (only the minimum identity which should be considered as a BLAST hit). Instead Easyfig just assumes the minimum similarity observed in the current blast-comparisons as minimum value.

While this can often be quite convenient, it makes it difficult to compare separate images created with Easyfig (comparing different subsets of sequences, where the observed minimum BLAST similarity may change).

Would it be possible to add an option to manually specify a distinct minimum value for the Color gradient in the "BLAST Options" menu?

**Comment by mjsull** [comment]
Hi jvollme, now when you set minimum blast identity in figure->blast the legend will show that value instead of the minimum found. This will work for the command-line version too with flag -i
