### ISSUE TITLE
problems with blast 

### ISSUE THREAD

**Issue by fifi-1990** [mjsull/Easyfig#8]
Hello, 

Can anyone help me with the Easyfig 2.2.2 program. I have downloaded the program, I am using a windows 64bit computer, I have had a go at the examples but when it comes to generating a figure for my work I run into some issues. 
I am aiming to compare a series of bacterial sequences (approx 23kb in length) to assess which genes are conserved in my regions of interest. 
I have added the annotation files but when I go to add the blast files I run into problems.  
I have manually downloaded blast onto my computer as doing it automatically didn't seem to work. When I go to 'add a blast file' I'm not too sure what I am suppose to add? 
I go into program files, find the NCBI folder, click on blast-2.6.0+, then do I go into the bin folder? Which files am I suppose to add? When I try say blastn and try to generate a figure it tells me too few blast files? 

I am very new to this and I would greatly appreciate anyone's advice. 

Thanks :)

**Comment by bawee** [comment]
Hi fifi-1990,

You shouldn't have to add anything in the box above 'add a blast file'. These files get generated when you click "Generate blastn files". As you have discovered, you may have to show easyfig where the blast programs executables are on your computer. In the menu bar click on "Blast" then "choose blast location". You only need to tell Easyfig where the blast bin folder is, it will detect the executables within the bin folder (i.e. blastn, tblastx)

**Comment by fifi-1990** [comment]
Thank you Bawee, 

So now it seems I am having problems with my annotation files. I have them saved in .txt format. 
I have taken them off of kegg and attempted to convert them to FASTA files using sequencher (but they still remain as .txt files). 

So I had gone to 'add folder' below the Annotation Files box and they uploaded, then I did as you suggested (thank you) and went and told the computer where the blast bin folder was located. 

When I pressed create figure, it now informs me that my .txt file(s) do not exist? 

So I guess I am also doing the annotation files wrong. 

Do you know what I am doing wrong, do I need to get these files from blast? To get a number like this?
>CP003856.1:2624547-2626148 Acinetobacter baumannii TYTH-1, complete genome

Any advice would be greatly appreciated.

**Comment by bawee** [comment]
Your feature file should be either a genbank or embl format file. Fasta files are fine too but you won't be able to draw any gene/CDS features. Easyfig might be looking for files that end with .fasta/.fas/.fa/.fna or .gb/.gbk/gbff. I would try adding 1 file at a time using the "add feature file" button.

For your A. baumanii example you could just download the entire gbk file directly from genbank and load that up (add feature file) into Easyfig. You can then tell easyfig to only use the subregion that you are interested in based on those coordinates.

**Comment by fifi-1990** [comment]
Hi, 

Thank you for your advice again. 
So I downloaded two whole bacterial chromosomal DNA sequences from NCBI and these are now .gb files. I have added each individually as a feature file. I go to the blast drop down menu up the top and choose blast location. I go to the NBCI file and tell it where the bin folder is. Once I do that, in the yellow box it then says 'Performing blastn...' (This writing does not change or dissapear)

On the right hand side of the save as box I choose a place for the figure to be saved. This will be on my desktop 

I click create figure. A box comes up with the heading No blast files. The text states that only gene figures will be drawn, continue? (To create a comparison figure please generate or manually input a blast file). 

I press yes and in the yellow box it tells me its drawing a figure. I figure is produced with very few and small/short blue arrows across the two black lines. I know this is not right, but I still don't understand what I am doing wrong? 

Do I need to be adding a blast file directly into the blast file box? 

Thank you for your help thus far, bawee. 

fifi-1990

**Comment by mjsull** [comment]
Hi,

There are a couple of things you need to do
A) If you're looking at the whole genome most genes will be too small to view and won't be drawn.
B) you need to generate the blast files, once you have loaded your genbank files click the generate blastn files button button before creating the Figure.

I would also suggest running through the examples on the wiki to get some idea of the features in Easyfig. https://github.com/mjsull/Easyfig/wiki/Tutorials

Best,

Mitchell
